# Sistemas de Ecuaciones Lineales

En este capitulo visitaremos el tema de los métodos numéricos para resolver sistemas lineas de ecuaciones simulataneas. Para poder explicar cada método  necesitaremos algunos sistemas lineales de prueba.

Un sistema lineal general de dos ecuaciones simulataneas y dos incognitas.
$$ a_{11} x_1 + a_{12} x_2 = b_1 \\ 
a_{21} x_1 + a_{22} x_2 = b_2 $$

El sistema anterior se puede escribir como una igualtad de de dos vectores:
$$
\begin{gather}
 \begin{bmatrix}
  a_{11} x_1 + a_{12} x_2 \\
  a_{21} x_1 + a_{22} x_2
 \end{bmatrix}
 =
  \begin{bmatrix}
   b_1\\
   b_2 
   \end{bmatrix}
\end{gather}
$$

Se puede reescribir la combinacion lineal de incognitas en forma de un producto matricial:
$$
\begin{gather}
 \begin{bmatrix}
  a_{11} & a_{12}\\
  a_{21} & a_{22}
 \end{bmatrix}
  \begin{bmatrix}
  x_1\\
  x_2
 \end{bmatrix}
 =
  \begin{bmatrix}
   b_1\\
   b_2 
   \end{bmatrix}
\end{gather}
$$
Se puede reescribir en forma compacta y general como:

$$
\mathbf A \mathbf x=\mathbf b
$$

Donde:
$$
\mathbf A=  
 \begin{bmatrix}
  a_{11} & a_{12}\\
  a_{21} & a_{22}
 \end{bmatrix}
$$

$$
\mathbf x= 
\begin{bmatrix}
  x_1\\
  x_2
 \end{bmatrix}
$$

$$
\mathbf b=
  \begin{bmatrix}
   b_1\\
   b_2 
   \end{bmatrix} 
$$
 
La matriz $\mathbf A$ es conocida como la *matriz de coeficientes*, el vector $ \mathbf x $ es conocido como el *vector de incognitas* y  $\mathbf b$ el *vector de terminos libres*.
 

## Rango, independecia lineal, transformaciones lineales


## Matrizes o trnasformaciones lineales importantes e inversa
El concepto de de transformacion lineal , es cualquier objeto u operacion que transforma un vector en otro vector. El producto matriz vector produce otro vector por lo tanto el sistema de ecuaciones lineales es una tranformacion linea.
Comunmente existe multiple tipos y grupos de tranformaciones. A continuacion expondremos casos de tranformaciones lineal mas comunes
### Identidad
la matriz identidad posee la propiedad de transformar un vector a sis mismo. en esencia no altera el vector de entrada. es equivalente a al elmento 0 en la suma o el elemento 1 en la multiplicacion.
Ejemplo de matriz identidad en 3  dimensiones.

$$
\mathbf I=  
 \begin{bmatrix}
  1 & 0 & 0\\
  0 & 1 & 0\\
  0 & 0 & 1
 \end{bmatrix}
$$

Se puede demostrar facilemente que la matriz que contiene 1 en la diagonal producira el mismo vector como $ \mathbf I \mathbf x= \mathbf x$.

La tranformacion inversa de la matriz identidad es ella misma $$ \mathbf I^{-1} = \mathbf I $$

### Escalado
La matriz que scala un vector estirandolo o comprimiendolo se conoce como scala y posee la siguiente estructura:
$$
\mathbf S=  
 \begin{bmatrix}
  s_1 & 0 & 0\\
  0 & s_2 & 0\\
  0 & 0 & s_3
 \end{bmatrix}
$$
En el caso de una escala homogenea $s_1=s_2=s_3=s$

### Distorsion cortante
$$
\mathbf F=  
 \begin{bmatrix}
  1 & s_{12} & 0\\
  0 & 1 & 0\\
  0 & 0 & 1
 \end{bmatrix}
$$

### Rotacion
Solo por mostrar un ejemplo la rotacion de un vector en el eje Z
$$
\mathbf R_z =  
 \begin{bmatrix}
  cos(\theta) & -sin(\theta) & 0\\
  sin(\theta) & cos(\theta) & 0\\
  0 & 0 & 1
 \end{bmatrix}
$$

### Matrices ortogonales
Son matrices que sus inversas son su transpuesta
$$ \mathbf Q^{-1} = \mathbf Q^T $$
Como ejemplo clasico la matrices de rotacion son matrices ortogonales.


### MAtrices simetricas
Sus elementos son simetricos a lo largo de la diagonal(ejemplo scalaado)
$$
\mathbf{Symm}=  
 \begin{bmatrix}
  x_1 & a & b\\
  a & x_2 & c\\
  b & c & x_3
 \end{bmatrix}
$$
Esto implica $ M^T = M $

### Matrices anti-simetricas
Sus elementos son de signo opuesto a lo largo de la diagonal(ejemplo rotacion)
$$
symm=  
 \begin{bmatrix}
  x_1 & a & b\\
  -a & x_2 & c\\
  -b & -c & x_3
 \end{bmatrix}
$$
Esto implica $ -K^T = K $

### Projecciones


## Systemas lineales y algunas definiciones:

In [1]:
import numpy as np


In [2]:
x1 = np.array([1,2,3]) 
x2 = np.array([3,7,10])
x3 = 2*x1
x4 = np.array([1,2,3,42,9,4,7,10,1,10]) 

aa = np.array([1,2,3,4,5,6,7,8,9])
aa = aa.reshape([3,3])


In [3]:
aa

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
aa = aa - 5*np.eye(3)


In [5]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
np.ones([4,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
np.eye(4)  

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [37]:
bb = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])  
bb[0:2,0:2] = np.zeros((2,2))
bb

array([[0, 0, 3],
       [0, 0, 6],
       [7, 8, 9]])

# Métodos Directos
MEtodos que utilizan una cantidad finita y restablecidad de pasos para determinar la solucion de un sistema lineal. Estos metodos.
## Reduccion Gausseana
Este metodo utilizado para resolver sistemas lineales utilizando el concepto de transformaciones lineales, y con ol objetivo de reducir el sistema lineal.
$$Ax = b$$
$$
A=  
 \begin{bmatrix}
  a & b & c\\
  d & e & f\\
  g & h & i
 \end{bmatrix}
$$

$$
b=  
 \begin{bmatrix}
  b_1\\
  b_2\\
  b_3
 \end{bmatrix}
$$

La matriz aumentada:
$$
\begin{array}{ccc|c}
  a & b & c & b_1\\
  d & e & f & b_2\\
  g & h & i & b_3
\end{array}
$$
Paso 1: normalizar  la primera fila con el elemento diagonal

$$
\begin{array}{ccc|c}
  \fbox 1 & \frac{b}{a} & \frac{c}{a} & \frac{b_1}{a}\\
  d & e & f & b_2\\
  g & h & i & b_3
\end{array}
$$

Paso 2: eliminar los elementos debajo del primer elemento de la diagonal
$fila_2 = fila_2 - d * fila_1$
$$
\begin{array}{ccc|c}
  1 & \frac{b}{a} & \frac{c}{a} & \frac{b_1}{a}\\
  \fbox 0 & e - d \frac{b}{a} & f - d \frac{c}{a} &b_2 -  \frac{d*b_1}{a} \\
  \fbox 0 & h - d*b/a & i - d*c/a
\end{array}
$$

Paso 3: nomalizar el segundo elemento de la diagonal

$$
\begin{array}{ccc|c}
  1 & b/a & c/a  & \frac{b_1}{a}\\
  0 & \fbox 1 & \frac{f - \frac{d c}{a}}{e - \frac{d b}{a}} & b_2 -  \frac{d*b_1}{a}\\
  0 & h - \frac{d b}{a} & i - \frac{d c}{a}
\end{array}
$$

Paso 3: Repetir el paso 2 con el siguiente elemento
$$
\begin{array}{ccc|c}
  1 & b/a & c/a & \frac{b_1}{a}\\
  0 & \fbox 1 & \frac{f - \frac{d c}{a}}{e - \frac{d b}{a}} &b_2 -  \frac{d*b_1}{a}\\
  0 & 0 & i - \frac{d c}{a} - (\frac{f - \frac{d c}{a}}{e - \frac{d b}{a}})(h - \frac{d b}{a})
\end{array}
$$

Paso 4: Normalizar el ultimo elemento de la diagonal
\begin{array}{ccc|c}
  1 & b/a & c/a & \frac{b_1}{a}\\
  0 & 1 & \frac{f - \frac{d c}{a}}{e - \frac{d b}{a}} &b_2 -  \frac{d*b_1}{a}\\
  0 & 0 & \fbox 1 & b'_3
\end{array}


En este punto el sistema linea debe de tener un triangulo de ceros debajo de la diagonal, y una diagonal de 1. En este punto la matriy esta "reducida". El siguiente paso se conoce como *substitucion  inversa*, este proceso comienza desde el ultimo elemento y se remplaza n la eqcuaciones hasta resolver todas las incognitas.

$$ x_3 =  b_3'$$

Y remplazamos en la fila 2 el valor de $x_3$

$$ x_2 = b'_2 - x_3*() $$

In [41]:
import numpy as np
import matplotlib.pyplot as plt

In [48]:
#Matriz de prueba
A = np.array( [ [10.0,3  ,2],
                [4   ,5  ,3],
                [1   ,10 ,20] ] )

b = np.array( [4, 6, 12] )


In [43]:
A[0,:] #Primera fila

array([10.,  3.,  2.])

In [12]:
A[1,:] #Segunda fila

array([4., 5., 3.])

In [13]:
A[2,:] #tercera fila

array([ 1., 10., 20.])

In [14]:
A[:,0] #Primera columna

array([10.,  4.,  1.])

In [15]:
#Elemento a_2,2
A[1,1]

5.0

In [16]:
#Modificar elemento
A[1,1] = 6
A

array([[10.,  3.,  2.],
       [ 4.,  6.,  3.],
       [ 1., 10., 20.]])

In [49]:
#Matriz aumentada (Augmented matrix)
Ab = np.zeros([3,4])
Ab[0:3, 0:3] = A
Ab[:,3] = b


A continuacion vamos a modificar la matriz para reducirla en su forma de triangulos de 0 utilizando el algoritmo de gauss:

In [18]:
#Paso1
Ab[0] = Ab[0] / Ab[0,0]
Ab

array([[ 1. ,  0.3,  0.2,  0.4],
       [ 4. ,  6. ,  3. ,  6. ],
       [ 1. , 10. , 20. , 12. ]])

In [19]:
#Paso 2
Ab[1] = Ab[1] - Ab[1,0]*Ab[0]
Ab[2] = Ab[2] - Ab[2,0]*Ab[0]
Ab

array([[ 1. ,  0.3,  0.2,  0.4],
       [ 0. ,  4.8,  2.2,  4.4],
       [ 0. ,  9.7, 19.8, 11.6]])

In [20]:
#Paso 3
Ab[1] = Ab[1] / Ab[1,1]
Ab

array([[ 1.        ,  0.3       ,  0.2       ,  0.4       ],
       [ 0.        ,  1.        ,  0.45833333,  0.91666667],
       [ 0.        ,  9.7       , 19.8       , 11.6       ]])

In [21]:
#paso 4
Ab[2] = Ab[2] - Ab[2,1]*Ab[1]
Ab

array([[ 1.        ,  0.3       ,  0.2       ,  0.4       ],
       [ 0.        ,  1.        ,  0.45833333,  0.91666667],
       [ 0.        ,  0.        , 15.35416667,  2.70833333]])

In [22]:
#Paso 5
Ab[2] = Ab[2] / Ab[2,2]
Ab

array([[1.        , 0.3       , 0.2       , 0.4       ],
       [0.        , 1.        , 0.45833333, 0.91666667],
       [0.        , 0.        , 1.        , 0.17639077]])

En las siguientes celdas vamos a resolver el sistema utilizand substitucion en reversa.

In [23]:
x3 = Ab[2,3]
x3

0.1763907734056987

In [24]:
x2 = Ab[1,3] - Ab[1,2]*x3
x2

0.8358208955223881

In [25]:
x1 = Ab[0,3] - Ab[0,2]*x3 - Ab[0,1]*x2
x1

0.11397557666214381

In [26]:
x = np.array([x1,x2,x3])
x

array([0.11397558, 0.8358209 , 0.17639077])

In [27]:
#Demostracion
A.dot(x)

array([ 4.,  6., 12.])

Algoritmo general para la reducción gaussiana

In [56]:
def gauss(Ab):        
    N = Ab.shape[0] #numero de filas

    for i in range(N):
        print("Fila#"+str(i))
        Ab[i] = Ab[i]/Ab[i,i] # Normalizacion de la fila cnel termino de la diagonal
        print(str(Ab))
        for j in range(i+1,N):
            print("Reduccion de la fila#"+str(j))
            Ab[j] = Ab[j] - (Ab[j,i] * Ab[i]) #Reduccion
            print(str(Ab))


def substitucion(Ab):
    #TODO: implmentar!
    N = Ab.shape[0] #numero de filas
    for i in range(N):
        print("Iteration i="+str(i))
        Ab[i] = Ab[i]/Ab[i,i] # Normalizacion de la fila con el termino de la diagonal
        for j in range(i+1,N):
            print("iteracion j="+str(j))
            Ab[j] = Ab[j] - (Ab[j,i] * Ab[i]) #Reduccion
            
def gauss_jordan(Ab):
    N = Ab.shape[0] #numero de filas
    for i in range(N):
        print("Fila#"+str(i))
        Ab[i] = Ab[i]/Ab[i,i] # Normalizacion de la fila cnel termino de la diagonal
        for j in range(i+1,N):
            #print("iteracion DOWN j="+str(j))
            Ab[j] = Ab[j] - (Ab[j,i] * Ab[i]) #Reduccion
            
        for j in range(i):
            #print("iteracion UP j="+str(j))
            Ab[j] = Ab[j] - (Ab[j,i] * Ab[i]) #Reduccion
            
        print(Ab)

In [57]:
Ab_ = Ab.copy()
Ab_

array([[10.,  3.,  2.,  4.],
       [ 4.,  5.,  3.,  6.],
       [ 1., 10., 20., 12.]])

In [58]:
gauss_jordan(Ab_)

Fila#0
[[ 1.   0.3  0.2  0.4]
 [ 0.   3.8  2.2  4.4]
 [ 0.   9.7 19.8 11.6]]
Fila#1
[[ 1.          0.          0.02631579  0.05263158]
 [ 0.          1.          0.57894737  1.15789474]
 [ 0.          0.         14.18421053  0.36842105]]
Fila#2
[[1.         0.         0.         0.05194805]
 [0.         1.         0.         1.14285714]
 [0.         0.         1.         0.02597403]]


In [70]:
AA = np.zeros([3,6])
AA[0:3 , 0:3] = A
AA[0:3 , 3:] = np.eye(3)
AA

array([[10.,  3.,  2.,  1.,  0.,  0.],
       [ 4.,  5.,  3.,  0.,  1.,  0.],
       [ 1., 10., 20.,  0.,  0.,  1.]])

In [71]:
gauss(AA)

Fila#0
[[ 1.   0.3  0.2  0.1  0.   0. ]
 [ 4.   5.   3.   0.   1.   0. ]
 [ 1.  10.  20.   0.   0.   1. ]]
Reduccion de la fila#1
[[ 1.   0.3  0.2  0.1  0.   0. ]
 [ 0.   3.8  2.2 -0.4  1.   0. ]
 [ 1.  10.  20.   0.   0.   1. ]]
Reduccion de la fila#2
[[ 1.   0.3  0.2  0.1  0.   0. ]
 [ 0.   3.8  2.2 -0.4  1.   0. ]
 [ 0.   9.7 19.8 -0.1  0.   1. ]]
Fila#1
[[ 1.          0.3         0.2         0.1         0.          0.        ]
 [ 0.          1.          0.57894737 -0.10526316  0.26315789  0.        ]
 [ 0.          9.7        19.8        -0.1         0.          1.        ]]
Reduccion de la fila#2
[[ 1.          0.3         0.2         0.1         0.          0.        ]
 [ 0.          1.          0.57894737 -0.10526316  0.26315789  0.        ]
 [ 0.          0.         14.18421053  0.92105263 -2.55263158  1.        ]]
Fila#2
[[ 1.          0.3         0.2         0.1         0.          0.        ]
 [ 0.          1.          0.57894737 -0.10526316  0.26315789  0.        ]
 [ 0.   

In [64]:
Ainv = AA[:, 3:]

In [69]:
Ainv.dot(A)

array([[ 1.00000000e+00,  6.07153217e-18,  2.60208521e-17],
       [ 4.85722573e-17,  1.00000000e+00, -2.77555756e-17],
       [ 9.71445147e-17,  8.32667268e-17,  1.00000000e+00]])

In [31]:
A_ = A.copy()
AI = np.c_[A,np.eye(3,3)]
AI

array([[10.,  3.,  2.,  1.,  0.,  0.],
       [ 4.,  6.,  3.,  0.,  1.,  0.],
       [ 1., 10., 20.,  0.,  0.,  1.]])

In [32]:
gauss_jordan(AI)

Iteration i=0
[[ 1.   0.3  0.2  0.1  0.   0. ]
 [ 0.   4.8  2.2 -0.4  1.   0. ]
 [ 0.   9.7 19.8 -0.1  0.   1. ]]
Iteration i=1
[[ 1.          0.          0.0625      0.125      -0.0625      0.        ]
 [ 0.          1.          0.45833333 -0.08333333  0.20833333  0.        ]
 [ 0.          0.         15.35416667  0.70833333 -2.02083333  1.        ]]
Iteration i=2
[[ 1.          0.          0.          0.12211669 -0.05427408 -0.00407056]
 [ 0.          1.          0.         -0.10447761  0.26865672 -0.02985075]
 [ 0.          0.          1.          0.04613297 -0.13161465  0.0651289 ]]


## Metodos iterativos

Los métodos iterativos son aquellos que aproximan la solucion en cada paso del algoritmo. Por lo tanto una solucion iterativa es necesaria, ademas una condicion de salida. Estos métodos son preferidos para matrices muy grandes, donde los metodos directos acumula mucho error de truncamiento debido a los calculos que involucran operacion de coma flotante. Los metodos iterativos se enfocan en descomponer el sistema original en un sistema facil de invertir, en el caso mas simple el método de jacobi descompone la matriz de coeficientes en una componente diagonal y el resto.

### Método de Jacobi
El Metodo de jacobi en esencia descompone la matriz de coefficientes $\mathbf A$

In [ ]:
A = D + P

### Método Gauss-Seidel