# Librerias para analisis de datos

## Contenido 
* Computacion numerica
  * Arreglos
  * Vectores
  * MAtrices

* Visualizacion
  * Introducción
  * Graficas de simples
  * Leyendas y comentarios en $\LaTeX$

* Introducción a Scipy
  * modulos
  * algebra lineal
  * Estadistica

* Computacion numerica

In [15]:
import numpy as np
#arreglo de 9 elementos (dimnesiones)
a = np.array([1,2,3,4,5,6,7,8,9])

# la forma del arreglo 
a.shape #(9,)

#una matriz  es un arreglo de forma 2 dos indices (dos dimensiones)
a = a.reshape([3,3])

#El producto de los tamaños de los indices tiene que ser el numero de elementos del arreglo
# 3x3 = 9
#a.reshape([filas,columna])


#Producto punto
print(a.dot(a))



[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


* Computación Simbolica

In [38]:
import sympy as sp
sp.init_printing()

In [56]:
x = sp.symbols("x")
f1 = x
f2 = sp.sin(x) * sp.cos(x)
f_ = sp.Array([f1,f2])
f_.diff(x)

In [58]:
f_.diff(x,6)

In [55]:
#clean script cell
!rm *.png
!rm *.tex

rm: *.png: No such file or directory
rm: *.tex: No such file or directory


In [8]:
#syn github repo 
!git add -A
!git commit -m "from script test (6.feb.2019)"
!git push origin master

[master 0b79051] from script
 3 files changed, 1388 insertions(+), 1996 deletions(-)
 rewrite 1_Intro.ipynb (63%)
Objekte aufzählen: 9, Fertig.
Zähle Objekte: 100% (9/9), Fertig.
Delta compression using up to 4 threads
Komprimiere Objekte: 100% (5/5), Fertig.
Schreibe Objekte: 100% (5/5), 13.90 KiB | 3.47 MiB/s, Fertig.
Total 5 (delta 4), reused 0 (delta 0)
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
To https://github.com/stivio00/NumericalMethodsJupyter.git
   bea85c1..0b79051  master -> master
